import React from 'react'
import { NavLink,Outlet, Routes } from 'react-router-dom'

export default function Products() {
  const navStyle = ({isActive})=>{
    return {
       fontWeight: isActive ? "bold" : "normal",
       textDecoration: isActive ? "none" : "underline"
    }
  }

  return (
    <div>
      <nav>
       <NavLink to="lyout" style={navStyle}>Lyout</NavLink>
       <NavLink to="feature" style={navStyle}>FeatureProduct</NavLink>
       </nav>
       <Outlet/>
       <p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod hendrerit massa nec venenatis. Nunc interdum risus elit, et posuere elit viverra id. Pellentesque sagittis molestie neque, pellentesque elementum tellus pharetra eu. Nulla ut nisl ante. Proin nec convallis mi. Integer finibus sapien est, vitae maximus enim tristique sed. Duis dapibus vestibulum urna, fringilla consequat est ultrices et.

Vivamus felis mi, scelerisque quis tristique in, fringilla in purus. Donec in ante consequat, imperdiet risus a, lobortis velit. Sed malesuada euismod neque sed pretium. Duis ut sem quis augue sollicitudin aliquam. Praesent neque leo, pharetra non lacus ac, lobortis convallis felis. Nullam aliquet dolor lectus, vitae varius ligula pulvinar non. Praesent libero lacus, feugiat cursus euismod id, convallis quis libero. Donec laoreet diam ipsum, in ultrices sapien facilisis et.

Suspendisse malesuada justo sapien, vel tincidunt metus feugiat vitae. Nullam a pretium mauris, nec commodo nulla. Ut mollis odio porttitor, eleifend mi sed, imperdiet magna. Nam ac cursus tellus. Fusce ac aliquam ex. Aliquam vel orci eget ex varius vestibulum. Vestibulum suscipit nisi ac tellus mattis semper. Donec pharetra luctus ex, quis tempus dui tristique mattis. Nullam in nisl sit amet mauris dapibus aliquet vitae placerat libero. Duis et porttitor nulla, sed mattis justo. Etiam sit amet leo sodales, porttitor elit at, efficitur eros.

Nunc mollis pharetra ligula ornare varius. In nec neque ut felis euismod ornare. Sed a mollis magna. Donec tempor nunc convallis urna convallis aliquet. Nullam porttitor turpis eu ante convallis elementum. Ut pharetra eget lacus non ullamcorper. Sed dapibus augue sit amet lorem cursus ullamcorper.

Integer leo lacus, elementum a augue id, laoreet vestibulum mi. Aliquam sed condimentum quam. Morbi quam mauris, sollicitudin quis fermentum a, dapibus eu sem. Nam a dui in nunc tristique dictum. Nulla sed orci non nisi finibus semper. Ut tempor augue in luctus consequat. Donec dictum lectus eu enim suscipit, dictum porttitor nisl porttitor. Curabitur nisi libero, porta tempus justo eget, suscipit vulputate lacus. Donec at justo at orci iaculis sodales at at nunc. Sed sagittis, leo consectetur volutpat placerat, lectus eros tempor elit, vel pharetra purus mauris eget orci. Morbi a cursus massa. Aliquam pretium eleifend diam eu egestas. Mauris ullamcorper congue diam, id dictum est interdum non. Nam venenatis, ex sed tristique dictum, sem mauris rutrum dui, in fringilla quam nibh non lorem. Etiam magna ipsum, convallis quis lacus nec, vehicula egestas lacus. Integer sapien neque, condimentum sed erat in, ornare vulputate sem.

Maecenas consectetur mi magna, vitae congue risus dignissim pulvinar. Morbi eget leo efficitur, commodo nunc a, laoreet odio. Sed at scelerisque tortor. Donec lobortis viverra sem eget rutrum. Proin bibendum efficitur lectus tempus condimentum. Mauris vel ante diam. Nunc condimentum pretium fermentum. Maecenas quis lobortis odio. Sed laoreet nibh interdum mauris vestibulum bibendum. Vestibulum accumsan augue quis facilisis viverra. Aliquam placerat pulvinar congue. Etiam ultricies facilisis sapien, sed dictum purus egestas et. In et metus nec sem scelerisque mattis varius et nulla. Vivamus malesuada pretium rhoncus. In finibus velit ut hendrerit dignissim.

Aenean commodo elit vel quam tempor, nec tincidunt nibh hendrerit. Nam vel tincidunt magna, sit amet pellentesque nulla. Nam vestibulum dui purus, nec auctor magna faucibus nec. Pellentesque commodo auctor turpis sit amet fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque vestibulum ultricies lorem, ut facilisis mauris vestibulum porttitor. Aliquam erat volutpat. Donec ultricies vitae arcu vel faucibus. Morbi ornare magna non tortor aliquet, tristique consectetur ligula luctus. Ut viverra tortor vel dui euismod, feugiat fringilla diam suscipit. Vestibulum eu purus finibus mauris vehicula consequat finibus a magna. Proin sit amet cursus enim. Nunc interdum neque at neque placerat, et dapibus nunc fringilla. Nulla vitae enim et leo tincidunt feugiat. Praesent at odio sit amet turpis commodo euismod. Ut eget hendrerit purus.

Vivamus id nibh vitae augue accumsan tincidunt. Vestibulum eget egestas leo, non consequat tellus. Nunc vel nulla felis. Fusce aliquet efficitur purus, ut porta turpis convallis sed. Fusce elit lectus, mollis nec nisi at, sagittis vehicula nisi. Nam dictum sem vel mauris sagittis gravida. Sed eu eros turpis. Nunc facilisis felis quis orci dictum, vitae varius enim pellentesque.

Aenean sed diam vulputate, vestibulum quam et, vestibulum mi. Pellentesque elit felis, scelerisque ac commodo ut, euismod at magna. Morbi ac dolor quis magna facilisis mollis malesuada at ipsum. Nunc sapien dui, blandit id laoreet quis, iaculis a lectus. Aliquam erat volutpat. Duis sed bibendum orci. Integer vitae enim tortor. Maecenas tempor eu ligula vitae interdum. Integer felis dolor, lobortis vulputate aliquet eget, rhoncus in libero.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec tincidunt venenatis eros sed tincidunt. Sed hendrerit vel nunc ac rhoncus. In cursus mi commodo nisi semper mollis. Aenean tempus quis eros eu egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean congue urna a ligula venenatis iaculis. Nullam molestie tempor orci, ut vulputate eros porta ut.

Morbi ut ultrices justo. Proin pellentesque massa ac sapien auctor tempor. Nullam ut sodales purus. Proin eu ex odio. Donec vulputate sapien ac sem vestibulum elementum. Quisque lacus quam, sagittis blandit accumsan non, interdum ac dui. Ut consequat ex vel diam rhoncus, quis consequat velit hendrerit. Proin iaculis dignissim turpis, sed blandit enim fringilla a. Integer sit amet tempus dui. Fusce vel laoreet risus, nec aliquam dolor. Fusce nec est ut velit aliquet mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In eleifend blandit pulvinar. Curabitur mollis dictum arcu. Etiam imperdiet at dolor sit amet luctus. In non tortor in metus ultrices sodales.

Cras sit amet augue ac lacus eleifend rhoncus. Vivamus eu mauris mattis, fringilla felis non, sagittis nisl. Duis sed aliquam elit. Sed imperdiet felis et eros mattis, sit amet convallis nunc blandit. Fusce gravida tempus tempor. Vestibulum nec semper enim. Fusce ut nulla ornare, elementum enim vel, lobortis leo. Sed id neque quis erat placerat congue vel vitae metus. Etiam commodo id felis at viverra. Maecenas sodales at enim a faucibus. Vestibulum metus libero, facilisis non ante non, scelerisque gravida orci.

Donec a blandit leo, in rutrum ante. Suspendisse bibendum porttitor ex, vel malesuada mi luctus ultricies. Proin efficitur ipsum et lorem blandit, ac congue ligula vestibulum. Vivamus purus dolor, mollis ac convallis eu, commodo ut felis. Proin viverra, est vel faucibus volutpat, erat arcu vulputate turpis, eu condimentum nisl arcu sit amet quam. Nam suscipit lectus et eros luctus ullamcorper. Proin vehicula, velit eget malesuada congue, neque justo vulputate mauris, eget venenatis lectus ante vitae lacus. Morbi venenatis gravida nulla et rutrum. Ut malesuada ex quis sapien volutpat, non sagittis elit dignissim. Praesent sagittis nulla eu sem varius interdum. Fusce lacinia felis ac ex semper, nec iaculis urna maximus. Mauris blandit ex libero, in dictum lectus suscipit non. Duis vulputate, erat non efficitur fringilla, odio orci fringilla sem, sed vehicula purus turpis at risus.

Pellentesque tincidunt iaculis urna non ultricies. Nulla facilisi. Sed eleifend, felis id pretium aliquet, odio ipsum blandit ex, quis pellentesque orci mauris id nulla. Nunc sapien felis, auctor non tortor bibendum, rhoncus sagittis elit. Integer mollis tellus vitae enim vestibulum dictum vel at est. Donec mi odio, aliquam vitae pretium rutrum, gravida vitae erat. Nulla nec mauris ac odio tincidunt aliquet. Sed est turpis, pulvinar eget felis eu, egestas pellentesque nulla. In quis ligula porttitor, rutrum tortor sed, consequat enim. Cras laoreet elit vitae risus tempor, sed imperdiet nulla cursus. Cras congue arcu eu tellus tempus, sed porta nulla imperdiet. Proin vehicula, diam a volutpat bibendum, purus felis aliquet diam, laoreet viverra massa diam ac lectus. Proin id facilisis est. Morbi ac lacinia risus, vitae molestie libero. Etiam a laoreet ligula.

Fusce feugiat nisl sit amet viverra scelerisque. Nam placerat felis neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras non augue eget sem rhoncus imperdiet. Cras imperdiet turpis id est cursus finibus. Sed sit amet odio ac orci faucibus pretium. Cras venenatis dapibus hendrerit. Donec lacinia ligula eget velit condimentum eleifend. Donec quis nisi nec felis ultrices eleifend. In hac habitasse platea dictumst. Proin rhoncus nisi id libero pretium, sed feugiat nisl rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Maecenas in euismod quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Pellentesque tortor eros, dictum at pretium id, finibus in lectus. Aliquam egestas odio at urna eleifend sagittis. Ut tincidunt ultrices ornare. Curabitur quis turpis non diam ultrices ullamcorper imperdiet vitae metus. Nullam dictum congue nibh, ut vulputate massa ultrices id. Nam eget turpis posuere, posuere dui in, aliquet nulla. Phasellus vehicula nisi justo, sit amet elementum augue eleifend et. Suspendisse eget iaculis ipsum. Suspendisse lorem eros, ornare quis mauris et, blandit blandit lectus. Fusce aliquam malesuada maximus. Proin elit urna, vehicula tincidunt magna auctor, molestie sagittis sapien. Nam interdum, risus id mattis venenatis, odio augue ullamcorper velit, vel ornare dolor tellus eget nisl. Morbi maximus nec odio in consequat. Aenean vitae facilisis turpis.

Aliquam sed augue eget diam aliquam auctor et posuere massa. Ut ultricies eget magna quis tempor. Maecenas iaculis, erat quis rhoncus facilisis, turpis magna lobortis lorem, ut ornare ex dolor at turpis. Duis pretium lorem pulvinar purus pharetra, varius suscipit eros pulvinar. Duis condimentum mi vitae purus euismod lobortis quis nec odio. Aenean vel lorem nec justo faucibus vulputate. Vestibulum pharetra lorem nisl, ut hendrerit eros maximus vestibulum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, ligula vel gravida sodales, diam tellus facilisis augue, ut sodales odio neque sed neque. Praesent id tortor placerat, porta enim vitae, volutpat nunc. Aliquam erat volutpat. Sed non commodo tellus, a malesuada lectus. Curabitur volutpat velit a erat ullamcorper, ut viverra est luctus.

Suspendisse sed auctor diam, eu sodales quam. Vestibulum ultrices aliquet elit, in sagittis massa faucibus vitae. Vestibulum eget dui et leo pretium ultrices in vitae urna. Fusce rhoncus aliquet purus, eget iaculis tellus volutpat vel. Nam massa odio, gravida blandit tristique quis, aliquam eget quam. Duis auctor, tortor eu aliquam cursus, tortor justo tempus nulla, sit amet fermentum ipsum dui vestibulum mauris. Vestibulum in vulputate urna. Phasellus finibus sapien felis, sed placerat augue congue quis. Etiam eget massa ac lacus semper scelerisque sed vitae lorem. Phasellus sit amet est a mi efficitur elementum quis non orci. Vivamus leo odio, egestas eget tincidunt id, imperdiet quis dolor. Aenean vulputate tellus sit amet purus tempus dignissim. Sed luctus nibh vitae turpis euismod, ut vulputate ligula sodales.

Vestibulum tristique vehicula tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin faucibus enim volutpat, congue risus vel, feugiat arcu. Proin ac nulla sit amet sapien ultricies maximus eu at nibh. In quis mollis orci. Sed volutpat velit ut sollicitudin blandit. Aenean vitae tempor nisl. Donec accumsan suscipit euismod. Sed pharetra dictum risus, quis dignissim tellus placerat semper. Proin at efficitur sapien.

Vestibulum lectus orci, porta at maximus suscipit, vestibulum a dolor. Aliquam malesuada ligula neque. Etiam ultricies elit vel orci faucibus auctor. Morbi porttitor a quam in mollis. Nullam elit mi, convallis in ornare ullamcorper, gravida quis lectus. Donec elementum, nisi ac posuere mattis, tellus quam auctor enim, eget condimentum quam leo eu est. In eu velit tincidunt, sodales mi ac, blandit nulla. Ut hendrerit, sem non commodo hendrerit, sem neque molestie turpis, non viverra neque velit non est. Aliquam commodo metus mi, vel vulputate velit mollis eget. </p>

    </div>
  )
}
